# Generated by Django 4.0.10 on 2024-08-06 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('referrer', models.CharField(max_length=20)),
                ('referrer_email', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PD', 'pending'), ('NA', 'On waiting list'), ('DX', 'Declined'), ('CL', 'Closed'), ('AP', 'Accepted Preston'), ('AB', 'Accepted BLackburn'), ('TP', 'Treatment Preston'), ('TB', 'Treatment BLackburn'), ('CP', 'Completed')], default='PD', max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='patient.patient')),
            ],
        ),
    ]
