# Generated by Django 4.0.10 on 2024-09-01 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='date_started',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending review'), ('WL', 'On waiting list'), ('DX', 'Declined'), ('CL', 'Closed'), ('AP', 'Accepted Preston'), ('AB', 'Accepted Blackburn'), ('TP', 'Treatment Preston'), ('TB', 'Treatment Blackburn'), ('CP', 'Completed')], default='PD', max_length=2),
        ),
    ]
