# Generated by Django 4.0.10 on 2024-09-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_referral_date_closed_referral_date_started_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='status',
            new_name='stage',
        ),
    ]
