# Generated by Django 4.0.10 on 2024-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_rename_status_referral_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
