# Generated by Django 4.0.10 on 2024-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nhs_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
