# Generated by Django 4.0.10 on 2025-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_notes', '0002_alter_progressnote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
