# Generated by Django 4.0.10 on 2025-04-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_notes', '0003_alter_progressnote_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressnote',
            old_name='notes_id',
            new_name='note_id',
        ),
    ]
